### ISSUE TITLE
where are intrinsics and exintrinsics? 

### ISSUE THREAD

**Issue by 9796l** [gmberton/CosPlace#48] opened 2024-09-02 08:00 UTC
i am very grateful for your great work. i want to use dataset to study,where are the  intrinsics and exintrinsics of the panorama? thank you very much for your soon response.

**Comment by gmberton** [comment] 2024-09-28 05:10
Duplicate of [this issue](https://github.com/gmberton/CosPlace/issues/46)

**Closed as completed by gmberton** 2024-09-28 05:10 UTC
